name: 24/7 Telegram Bot Runner

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - run: pip install aiogram aiohttp
    - name: Run Bot
      env:
        BOT_TOKEN: "${{ secrets.BOT_TOKEN }}"
        CRYPTO_PAY_TOKEN: "${{ secrets.CRYPTO_PAY_TOKEN }}"
        ADMIN_ID: "${{ secrets.ADMIN_ID }}"
        CHANNEL_ID: "${{ secrets.CHANNEL_ID }}"
      run: |
        until python main_vps.py; do
          echo "Crashed. Restarting..."
          sleep 5
        done
